# Generated by Django 5.1.1 on 2026-07-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=50, unique=True, verbose_name='Member ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('baptism_name', models.CharField(blank=True, max_length=200, verbose_name='Baptism Name')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('yenesha_abat', models.CharField(blank=True, max_length=200, verbose_name='Yenesha Abat')),
                ('membership_date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='Phone Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Member')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['member_id'], name='membership__member__cea165_idx'), models.Index(fields=['full_name'], name='membership__full_na_99e641_idx'), models.Index(fields=['phone_number'], name='membership__phone_n_2ac5ae_idx'), models.Index(fields=['is_active'], name='membership__is_acti_95769f_idx')],
            },
        ),
    ]
