# Generated by Django 5.1.1 on 2026-07-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Member ID'),
        ),
    ]
