# Generated by Django 5.1.1 on 2026-07-24 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_alter_member_member_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_date',
            field=models.DateField(blank=True, null=True, verbose_name='Membership Date'),
        ),
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Application ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('baptism_name', models.CharField(blank=True, max_length=200, verbose_name='Baptism Name')),
                ('yenesha_abat', models.CharField(blank=True, max_length=200, verbose_name='Yenesha Abat')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('am', 'Amharic'), ('both', 'English and Amharic')], default='both', max_length=10, verbose_name='Preferred Language')),
                ('household_information', models.TextField(blank=True, verbose_name='Family or Household Information')),
                ('message', models.TextField(blank=True, verbose_name='Additional Message')),
                ('consent_confirmed', models.BooleanField(default=False, verbose_name='Consent Confirmed')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True, verbose_name='Decision Notes')),
                ('approved_member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_application', to='membership.member')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_membership_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['application_id'], name='membership__applica_66b486_idx'), models.Index(fields=['status'], name='membership__status_fddb44_idx'), models.Index(fields=['full_name'], name='membership__full_na_3ec284_idx'), models.Index(fields=['submitted_at'], name='membership__submitt_1b0f5f_idx')],
            },
        ),
    ]
