# Generated by Django 5.1.1 on 2026-07-20 03:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_am', models.CharField(blank=True, max_length=200)),
                ('body_en', models.TextField(blank=True)),
                ('body_am', models.TextField(blank=True)),
                ('link_url', models.URLField(blank=True)),
                ('link_label_en', models.CharField(blank=True, max_length=80)),
                ('link_label_am', models.CharField(blank=True, max_length=80)),
                ('priority', models.CharField(choices=[('info', 'Information'), ('important', 'Important'), ('urgent', 'Urgent')], default='info', max_length=20)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-priority', '-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ClergyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title_en', models.CharField(max_length=150)),
                ('title_am', models.CharField(blank=True, max_length=150)),
                ('bio_en', models.TextField(blank=True)),
                ('bio_am', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_am', models.CharField(blank=True, max_length=200)),
                ('description_en', models.TextField(blank=True)),
                ('description_am', models.TextField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('registration_url', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_en', models.CharField(max_length=150)),
                ('name_am', models.CharField(blank=True, max_length=150)),
                ('summary_en', models.TextField()),
                ('summary_am', models.TextField(blank=True)),
                ('audience_en', models.CharField(blank=True, max_length=150)),
                ('audience_am', models.CharField(blank=True, max_length=150)),
                ('image_url', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='SacramentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('baptism', 'Baptism'), ('wedding', 'Holy Matrimony'), ('memorial', 'Memorial / Funeral'), ('counseling', 'Spiritual Counseling'), ('confession', 'Confession Appointment'), ('certificate', 'Certificate / Church Record'), ('other', 'Other')], max_length=30)),
                ('requester_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('consent_to_contact', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_am', models.CharField(blank=True, max_length=200)),
                ('speaker', models.CharField(blank=True, max_length=150)),
                ('scripture_reference', models.CharField(blank=True, max_length=100)),
                ('preached_on', models.DateField()),
                ('language', models.CharField(choices=[('am', 'Amharic'), ('en', 'English'), ('gez', "Ge'ez"), ('mixed', 'Mixed')], default='am', max_length=10)),
                ('youtube_url', models.URLField()),
                ('summary_en', models.TextField(blank=True)),
                ('summary_am', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-preached_on'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=150)),
                ('name_am', models.CharField(blank=True, max_length=150)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('note_en', models.CharField(blank=True, max_length=250)),
                ('note_am', models.CharField(blank=True, max_length=250)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['day_of_week', 'sort_order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name_en', models.CharField(default='St. Urael Ethiopian Orthodox Tewahedo Church', max_length=200)),
                ('church_name_am', models.CharField(blank=True, default='ቅዱስ ኡራኤል ኢትዮጵያዊ ኦርቶዶክስ ተዋሕዶ ቤተ ክርስቲያን', max_length=200)),
                ('short_name', models.CharField(default='St. Urael Church', max_length=100)),
                ('motto_en', models.CharField(blank=True, default='Faith, worship, learning, and community', max_length=250)),
                ('motto_am', models.CharField(blank=True, default='እምነት፣ አምልኮ፣ ትምህርት እና ማኅበረሰብ', max_length=250)),
                ('welcome_en', models.TextField(blank=True, default='A welcoming Ethiopian Orthodox Tewahedo Christian community serving families, children, youth, and visitors.')),
                ('welcome_am', models.TextField(blank=True, default='ቤተሰቦችን፣ ሕፃናትን፣ ወጣቶችን እና እንግዶችን የሚያገለግል እንግዳ ተቀባይ የኢትዮጵያ ኦርቶዶክስ ተዋሕዶ ክርስቲያናዊ ማኅበረሰብ።')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('office_hours', models.CharField(blank=True, max_length=200)),
                ('map_url', models.URLField(blank=True)),
                ('livestream_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('donation_url', models.URLField(blank=True)),
                ('sunday_school_url', models.CharField(blank=True, default='/accounts/login/', max_length=255)),
                ('hero_image_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
