# Generated by Django 5.1.1 on 2026-06-14 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('feast', 'Feast'), ('fast', 'Fast'), ('class', 'Class'), ('mezmur', 'Mezmur Practice'), ('parent_meeting', 'Parent Meeting'), ('competition', 'Bible Competition'), ('other', 'Other')], default='other', max_length=50)),
                ('is_recurring', models.BooleanField(default=False)),
                ('is_orthodox_calendar_event', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date', 'title'],
                'indexes': [models.Index(fields=['start_date'], name='calendar_ap_start_d_2e9a42_idx'), models.Index(fields=['event_type'], name='calendar_ap_event_t_317962_idx'), models.Index(fields=['created_at'], name='calendar_ap_created_89045d_idx')],
            },
        ),
    ]
