# Generated by Django 5.1.1 on 2026-06-14 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=50)),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('homework_completion', models.PositiveIntegerField(default=0)),
                ('participation', models.PositiveIntegerField(default=0)),
                ('memory_verses', models.PositiveIntegerField(default=0)),
                ('prayer_memorization', models.PositiveIntegerField(default=0)),
                ('mezmur_participation', models.PositiveIntegerField(default=0)),
                ('behavior_respect', models.PositiveIntegerField(default=0)),
                ('church_service_participation', models.PositiveIntegerField(default=0)),
                ('teacher_comments', models.TextField(blank=True)),
                ('parent_notes', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_progress_reports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='students.student')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['student'], name='reports_pro_student_aa638c_idx'), models.Index(fields=['period'], name='reports_pro_period_57d02f_idx'), models.Index(fields=['generated_at'], name='reports_pro_generat_f5f5ab_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'period'), name='unique_progress_report_per_student_period')],
            },
        ),
    ]
