# Generated by Django 5.1.1 on 2026-06-14 19:13

import announcements.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('target', models.CharField(choices=[('all', 'All'), ('class', 'Class')], default='all', max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='announcements/')),
                ('youtube_link', models.URLField(blank=True, validators=[announcements.models.validate_youtube_url])),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='classes.classlevel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target'], name='announcemen_target_c0c66b_idx'), models.Index(fields=['class_level'], name='announcemen_class_l_e0e77b_idx'), models.Index(fields=['created_at'], name='announcemen_created_40a59f_idx')],
            },
        ),
    ]
