# Generated by Django 5.1.1 on 2026-06-27 16:02

import announcements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='attachment',
            field=models.FileField(blank=True, upload_to='announcements/files/', validators=[announcements.models.validate_announcement_attachment]),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, upload_to='announcements/images/'),
        ),
    ]
