# Generated by Django 5.1.1 on 2026-06-14 19:13

import django.db.models.deletion
import resources.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('bible_stories', 'Bible Stories'), ('prayers', 'Prayers'), ('mezmur', 'Mezmur'), ('saints', 'Saints'), ('church_history', 'Church History'), ('fasting_feast', 'Fasting and Feast Days'), ('memory_verses', 'Memory Verses'), ('parent_resources', 'Parent Resources'), ('homework_support', 'Homework Support')], max_length=50)),
                ('file', models.FileField(blank=True, upload_to='resources/')),
                ('external_link', models.URLField(blank=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('am', 'Amharic'), ('gez', 'Ge’ez'), ('mixed', 'Mixed')], default='en', max_length=20)),
                ('topic', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='classes.classlevel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'title'],
                'indexes': [models.Index(fields=['category'], name='resources_r_categor_8e2710_idx'), models.Index(fields=['class_level'], name='resources_r_class_l_8ebf3c_idx'), models.Index(fields=['language'], name='resources_r_languag_9b288a_idx'), models.Index(fields=['created_at'], name='resources_r_created_215cda_idx')],
            },
        ),
        migrations.CreateModel(
            name='YouTubeResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('youtube_url', models.URLField(validators=[resources.models.validate_youtube_url])),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('bible_stories', 'Bible Stories'), ('prayers', 'Prayers'), ('mezmur', 'Mezmur'), ('saints', 'Saints'), ('church_history', 'Church History'), ('fasting_feast', 'Fasting and Feast Days'), ('memory_verses', 'Memory Verses'), ('parent_resources', 'Parent Resources'), ('homework_support', 'Homework Support')], max_length=50)),
                ('language', models.CharField(choices=[('en', 'English'), ('am', 'Amharic'), ('gez', 'Ge’ez'), ('mixed', 'Mixed')], default='en', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youtube_resources', to='classes.classlevel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'title'],
                'indexes': [models.Index(fields=['category'], name='resources_y_categor_25dac2_idx'), models.Index(fields=['class_level'], name='resources_y_class_l_c115c7_idx'), models.Index(fields=['created_at'], name='resources_y_created_308da3_idx')],
            },
        ),
    ]
