# Generated by Django 5.1.1 on 2026-06-27 16:36

import django.db.models.deletion
import resources.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtuberesource',
            name='class_level',
        ),
        migrations.RemoveField(
            model_name='youtuberesource',
            name='created_by',
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='resource',
            name='resources_r_categor_8e2710_idx',
        ),
        migrations.RemoveIndex(
            model_name='resource',
            name='resources_r_languag_9b288a_idx',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='category',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='external_link',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='language',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='topic',
        ),
        migrations.AddField(
            model_name='resource',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resource',
            name='youtube_link',
            field=models.URLField(blank=True, validators=[resources.models.validate_youtube_url]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, upload_to='resources/files/', validators=[resources.models.validate_resource_file]),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['is_published'], name='resources_r_is_publ_7afbcf_idx'),
        ),
        migrations.DeleteModel(
            name='YouTubeResource',
        ),
    ]
